<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CountriesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {

        $sql = "INSERT INTO countries (id, country, code,include) VALUES
            (1, 'ARUBA', 'ABW', 0),
            (2, 'AFGHANISTAN', 'AFG', 0),
            (3, 'ANGOLA', 'AGO', 0),
            (4, 'ANGUILLA', 'AIA', 0),
            (5, 'ALBANIA', 'ALB', 0),
            (6, 'ANDORRA', 'AND', 0),
            (7, 'NETHERLANDS ANTILLES', 'ANT', 0),
            (8, 'UNITED ARAB EMIRATES', 'ARE', 0),
            (9, 'ARGENTINA', 'ARG', 0),
            (10, 'ARMENIA', 'ARM', 0),
            (11, 'AMERICAN SAMOA', 'ASM', 0),
            (12, 'ANTARCTICA', 'ATA', 0),
            (13, 'FRENCH SOUTHERN TERRITORIES', 'ATF', 0),
            (14, 'ANTIGUA AND BARBUDA', 'ATG', 0),
            (15, 'AUSTRALIA', 'AUS', 0),
            (16, 'AUSTRIA', 'AUT', 0),
            (17, 'AZERBAIJAN', 'AZE', 0),
            (18, 'BURUNDI', 'BDI', 0),
            (19, 'BELGIUM', 'BEL', 0),
            (20, 'BENIN', 'BEN', 0),
            (21, 'BURKINA FASO', 'BFA', 0),
            (22, 'BANGLADESH', 'BGD', 0),
            (23, 'BULGARIA', 'BGR', 0),
            (24, 'BAHRAIN', 'BHR', 0),
            (25, 'BAHAMAS', 'BHS', 0),
            (26, 'BOSNIA AND HERZEGOVINA', 'BIH', 0),
            (27, 'BELARUS', 'BLR', 0),
            (28, 'BELIZE', 'BLZ', 0),
            (29, 'BERMUDA', 'BMU', 0),
            (30, 'BOLIVIA', 'BOL', 0),
            (31, 'BRAZIL', 'BRA', 0),
            (32, 'BARBADOS', 'BRB', 0),
            (33, 'BRUNEI', 'BRN', 0),
            (34, 'BHUTAN', 'BTN', 0),
            (35, 'BOUVET ISLAND', 'BVT', 0),
            (36, 'BOTSWANA', 'BWA', 0),
            (37, 'CENTRAL AFRICAN REPUBLIC', 'CAF', 0),
            (38, 'CANADA', 'CAN', 0),
            (39, 'COCOS (KEELING) ISLANDS', 'CCK', 0),
            (40, 'SWITZERLAND', 'CHE', 0),
            (41, 'CHILE', 'CHL', 0),
            (42, 'CHINA', 'CHN', 0),
            (44, 'CAMEROON', 'CMR', 0),
            (45, 'CONGO', 'COD', 0),
            (46, 'COOK ISLANDS', 'COK', 0),
            (47, 'COLOMBIA', 'COL', 0),
            (48, 'COMOROS', 'COM', 0),
            (49, 'CAPE VERDE', 'CPV', 0),
            (50, 'COSTA RICA', 'CRI', 0),
            (51, 'CUBA', 'CUB', 0),
            (52, 'CHRISTMAS ISLAND', 'CXR', 0),
            (53, 'CAYMAN ISLANDS', 'CYM', 0),
            (54, 'CYPRUS', 'CYP', 0),
            (55, 'CZECH REPUBLIC', 'CZE', 0),
            (56, 'GERMANY', 'DEU', 0),
            (57, 'DJIBOUTI', 'DJI', 0),
            (58, 'DOMINICA', 'DMA', 0),
            (59, 'DENMARK', 'DNK', 0),
            (60, 'DOMINICAN REPUBLIC', 'DOM', 0),
            (61, 'ALGERIA', 'DZA', 0),
            (62, 'ECUADOR', 'ECU', 0),
            (63, 'EGYPT', 'EGY', 0),
            (64, 'ERITREA', 'ERI', 0),
            (65, 'WESTERN SAHARA', 'ESH', 0),
            (66, 'SPAIN', 'ESP', 0),
            (67, 'ESTONIA', 'EST', 0),
            (68, 'ETHIOPIA', 'ETH', 0),
            (69, 'FINLAND', 'FIN', 0),
            (70, 'FIJI ISLANDS', 'FJI', 0),
            (71, 'FALKLAND ISLANDS', 'FLK', 0),
            (72, 'FRANCE', 'FRA', 0),
            (73, 'FAROE ISLANDS', 'FRO', 0),
            (74, 'MICRONESIA', 'FSM', 0),
            (75, 'GABON', 'GAB', 0),
            (76, 'UNITED KINGDOM', 'GBR', 0),
            (77, 'GEORGIA', 'GEO', 0),
            (78, 'GHANA', 'GHA', 0),
            (79, 'GIBRALTAR', 'GIB', 0),
            (80, 'GUINEA', 'GIN', 0),
            (81, 'GUADELOUPE', 'GLP', 0),
            (82, 'GAMBIA', 'GMB', 0),
            (83, 'GUINEA-BISSAU', 'GNB', 0),
            (84, 'EQUATORIAL GUINEA', 'GNQ', 0),
            (85, 'GREECE', 'GRC', 0),
            (86, 'GRENADA', 'GRD', 0),
            (87, 'GREENLAND', 'GRL', 0),
            (88, 'GUATEMALA', 'GTM', 0),
            (89, 'FRENCH GUIANA', 'GUF', 0),
            (90, 'GUAM', 'GUM', 0),
            (91, 'GUYANA', 'GUY', 0),
            (92, 'HONG KONG', 'HKG', 0),
            (93, 'HEARD ISLAND AND MCDONALD ISLANDS', 'HMD', 0),
            (94, 'HONDURAS', 'HND', 0),
            (95, 'CROATIA', 'HRV', 0),
            (96, 'HAITI', 'HTI', 0),
            (97, 'HUNGARY', 'HUN', 0),
            (98, 'INDONESIA', 'IDN', 0),
            (99, 'INDIA', 'IND', 0),
            (100, 'BRITISH INDIAN OCEAN TERRITORY', 'IOT', 0),
            (101, 'IRELAND', 'IRL', 0),
            (102, 'IRAN', 'IRN', 0),
            (103, 'IRAQ', 'IRQ', 0),
            (104, 'ICELAND', 'ISL', 0),
            (105, 'ISRAEL', 'ISR', 0),
            (106, 'ITALY', 'ITA', 0),
            (107, 'JAMAICA', 'JAM', 0),
            (108, 'JORDAN', 'JOR', 0),
            (109, 'JAPAN', 'JPN', 0),
            (110, 'KAZAKSTAN', 'KAZ', 0),
            (111, 'KENYA', 'KEN', 0),
            (112, 'KYRGYZSTAN', 'KGZ', 0),
            (113, 'CAMBODIA', 'KHM', 0),
            (114, 'KIRIBATI', 'KIR', 0),
            (115, 'SAINT KITTS AND NEVIS', 'KNA', 0),
            (116, 'SOUTH KOREA', 'KOR', 0),
            (117, 'KUWAIT', 'KWT', 0),
            (118, 'LAOS', 'LAO', 0),
            (119, 'LEBANON', 'LBN', 0),
            (120, 'LIBERIA', 'LBR', 0),
            (121, 'LIBYAN ARAB JAMAHIRIYA', 'LBY', 0),
            (122, 'SAINT LUCIA', 'LCA', 0),
            (123, 'LIECHTENSTEIN', 'LIE', 0),
            (124, 'SRI LANKA', 'LKA', 0),
            (125, 'LESOTHO', 'LSO', 0),
            (126, 'LITHUANIA', 'LTU', 0),
            (127, 'LUXEMBOURG', 'LUX', 0),
            (128, 'LATVIA', 'LVA', 0),
            (129, 'MACAO', 'MAC', 0),
            (130, 'MOROCCO', 'MAR', 0),
            (131, 'MONACO', 'MCO', 0),
            (132, 'MOLDOVA', 'MDA', 0),
            (133, 'MADAGASCAR', 'MDG', 0),
            (134, 'MALDIVES', 'MDV', 0),
            (135, 'MEXICO', 'MEX', 1),
            (136, 'MARSHALL ISLANDS', 'MHL', 0),
            (137, 'MACEDONIA', 'MKD', 0),
            (138, 'MALI', 'MLI', 0),
            (139, 'MALTA', 'MLT', 0),
            (140, 'MYANMAR', 'MMR', 0),
            (141, 'MONGOLIA', 'MNG', 0),
            (142, 'NORTHERN MARIANA ISLANDS', 'MNP', 0),
            (143, 'MOZAMBIQUE', 'MOZ', 0),
            (144, 'MAURITANIA', 'MRT', 0),
            (145, 'MONTSERRAT', 'MSR', 0),
            (146, 'MARTINIQUE', 'MTQ', 0),
            (147, 'MAURITIUS', 'MUS', 0),
            (148, 'MALAWI', 'MWI', 0),
            (149, 'MALAYSIA', 'MYS', 0),
            (150, 'MAYOTTE', 'MYT', 0),
            (151, 'NAMIBIA', 'NAM', 0),
            (152, 'NEW CALEDONIA', 'NCL', 0),
            (153, 'NIGER', 'NER', 0),
            (154, 'NORFOLK ISLAND', 'NFK', 0),
            (155, 'NIGERIA', 'NGA', 0),
            (156, 'NICARAGUA', 'NIC', 0),
            (157, 'NIUE', 'NIU', 0),
            (158, 'NETHERLANDS', 'NLD', 0),
            (159, 'NORWAY', 'NOR', 0),
            (160, 'NEPAL', 'NPL', 0),
            (161, 'NAURU', 'NRU', 0),
            (162, 'NEW ZEALAND', 'NZL', 0),
            (163, 'OMAN', 'OMN', 0),
            (164, 'PAKISTAN', 'PAK', 0),
            (165, 'PANAMA', 'PAN', 0),
            (166, 'PITCAIRN', 'PCN', 0),
            (167, 'PERU', 'PER', 0),
            (168, 'PHILIPPINES', 'PHL', 0),
            (169, 'PALAU', 'PLW', 0),
            (170, 'PAPUA NEW GUINEA', 'PNG', 0),
            (171, 'POLAND', 'POL', 0),
            (172, 'PUERTO RICO', 'PRI', 0),
            (173, 'NORTH KOREA', 'PRK', 0),
            (174, 'PORTUGAL', 'PRT', 0),
            (175, 'PARAGUAY', 'PRY', 0),
            (176, 'PALESTINE', 'PSE', 0),
            (177, 'FRENCH POLYNESIA', 'PYF', 0),
            (178, 'QATAR', 'QAT', 0),
            (179, 'RÏ¿½UNION', 'REU', 0),
            (180, 'ROMANIA', 'ROM', 0),
            (181, 'RUSSIAN FEDERATION', 'RUS', 0),
            (182, 'RWANDA', 'RWA', 0),
            (183, 'SAUDI ARABIA', 'SAU', 0),
            (184, 'SUDAN', 'SDN', 0),
            (185, 'SENEGAL', 'SEN', 0),
            (186, 'SINGAPORE', 'SGP', 0),
            (187, 'SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS', 'SGS', 0),
            (188, 'SAINT HELENA', 'SHN', 0),
            (189, 'SVALBARD AND JAN MAYEN', 'SJM', 0),
            (190, 'SOLOMON ISLANDS', 'SLB', 0),
            (191, 'SIERRA LEONE', 'SLE', 0),
            (192, 'EL SALVADOR', 'SLV', 0),
            (193, 'SAN MARINO', 'SMR', 0),
            (194, 'SOMALIA', 'SOM', 0),
            (195, 'SAINT PIERRE AND MIQUELON', 'SPM', 0),
            (196, 'SAO TOME AND PRINCIPE', 'STP', 0),
            (197, 'SURINAME', 'SUR', 0),
            (198, 'SLOVAKIA', 'SVK', 0),
            (199, 'SLOVENIA', 'SVN', 0),
            (200, 'SWEDEN', 'SWE', 0),
            (201, 'SWAZILAND', 'SWZ', 0),
            (202, 'SEYCHELLES', 'SYC', 0),
            (203, 'SYRIA', 'SYR', 0),
            (204, 'TURKS AND CAICOS ISLANDS', 'TCA', 0),
            (205, 'CHAD', 'TCD', 0),
            (206, 'TOGO', 'TGO', 0),
            (207, 'THAILAND', 'THA', 0),
            (208, 'TAJIKISTAN', 'TJK', 0),
            (209, 'TOKELAU', 'TKL', 0),
            (210, 'TURKMENISTAN', 'TKM', 0),
            (211, 'EAST TIMOR', 'TMP', 0),
            (212, 'TONGA', 'TON', 0),
            (213, 'TRINIDAD AND TOBAGO', 'TTO', 0),
            (214, 'TUNISIA', 'TUN', 0),
            (215, 'TURKEY', 'TUR', 0),
            (216, 'TUVALU', 'TUV', 0),
            (217, 'TAIWAN', 'TWN', 0),
            (218, 'TANZANIA', 'TZA', 0),
            (219, 'UGANDA', 'UGA', 0),
            (220, 'UKRAINE', 'UKR', 0),
            (221, 'UNITED STATES MINOR OUTLYING ISLANDS', 'UMI', 0),
            (222, 'URUGUAY', 'URY', 0),
            (223, 'UNITED STATES', 'USA', 0),
            (224, 'UZBEKISTAN', 'UZB', 0),
            (225, 'HOLY SEE (VATICAN CITY STATE)', 'VAT', 0),
            (226, 'SAINT VINCENT AND THE GRENADINES', 'VCT', 0),
            (227, 'VENEZUELA', 'VEN', 0),
            (228, 'VIRGIN ISLANDS', 'VGB', 0),
            (229, 'VIRGIN ISLANDS 2', 'VIR', 0),
            (230, 'VIETNAM', 'VNM', 0),
            (231, 'VANUATU', 'VUT', 0),
            (232, 'WALLIS AND FUTUNA', 'WLF', 0),
            (233, 'SAMOA', 'WSM', 0),
            (234, 'YEMEN', 'YEM', 0),
            (235, 'YUGOSLAVIA', 'YUG', 0),
            (236, 'SOUTH AFRICA', 'ZAF', 0),
            (237, 'ZAMBIA', 'ZMB', 0),
            (238, 'ZIMBABWE', 'ZWE', 0);";
        DB::update($sql);


    }
}
