<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class PartSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('parts')->truncate();
        $sql= "INSERT INTO parts VALUES
            (1,'Cabeza'),
            (2,'Cuerpo'),
            (3,'Body Interno'),
            (4,'Out Fit 1'),
            (5,'Out Fit 2'),
            (6,'Zapatos'),
            (7,'Accesorios'),
            (8,'Objeto'),
            (9,'Tamaño'),
            (10,'Fibra'),
            (11,'SV'),
            (12,'Pila'),
            (13,'Cargador'),
            (14,'Rostro'),
            (15,'Cejas'),
            (16,'Pestañas'),
            (17,'Parpado'),
            (18,'Pupila'),
            (19,'Iris'),
            (20,'Esclerotica'),
            (21,'Brillo'),
            (22,'Nariz'),
            (23,'Fosas'),
            (24,'Labios'),
            (25,'Boca'),
            (26,'Dientes'),
            (27,'Barba'),
            (28,'Bigote'),
            (29,'Lengua'),
            (30,'Cabello'),
            (31,'Orejas'),
            (32,'Lentes'),
            (33,'Modelo'),
            (34,'Estatura'),
            (35,'Forma'),
            (36,'Espuma'),
            (37,'Polyfoam'),
            (38,'Full'),
            (39,'Print'),
            (40,'Gluteos'),
            (41,'Guantes'),
            (42,'Dedos'),
            (43,'Panza'),
            (44,'Cuello'),
            (45,'Pecho'),
            (46,'Brazo'),
            (47,'Muñeca'),
            (48,'Palma'),
            (49,'Mano'),
            (50,'Uñas/Garras'),
            (51,'Abdomen'),
            (52,'Espalda'),
            (53,'Antebrazo'),
            (54,'Muslo'),
            (55,'Pierna'),
            (56,'Pantorrila'),
            (57,'Relleno'),
            (58,'Completo'),
            (59,'Color'),
            (60,'Ubicacion'),
            (61,'Pantorrilla'),
            (62,'Camisa'),
            (63,'Saco'),
            (64,'Panalón'),
            (65,'Calcetas'),
            (66,'Talla'),
            (67,'Full Print'),
            (68,'Playera'),
            (69,'Short'),
            (70,'Pans'),
            (71,'Parte Alta'),
            (72,'Parte Media'),
            (73,'Parte Baja'),
            (74,'Izquierda'),
            (75,'Derecha'),
            (76,'Frontal'),
            (77,'Atras'),
            (78,'Franjas'),
            (79,'Suela'),
            (80,'Entre Suela'),
            (81,'Lengueta'),
            (82,'Ojillos'),
            (83,'Agujeta'),
            (84,'Gorra'),
            (85,'Aretes'),
            (86,'Estetoscopio'),
            (87,'Mochila'),
            (88,'Bandera'),
            (89,'Paliacate'),
            (90,'Reloj'),
            (91,'Guitarra');";
        DB::update($sql);
    }
}
